# ---------------------------------------------------------------------------
# 23_supplementary_tables.R
#
# Builds every table of the Supplementary Results document directly from the
# analysis data and the saved partitioning fits, so no number is transcribed
# by hand. Everything uses the Flag-determinate samples reported in the paper
# (balanced 24,948 persons; all-available 29,169 persons) and the fixed
# reference age of 62.15 years used in Analysis/15-22.
#
#   Table S1   Primary longitudinal model, full sample (all coefficients,
#              joint tests, model-implied values at three ages)
#   Table S2   Observed means by assessment; equal-change check by domain
#   Table S3   Immigrant vs non-immigrant, elementwise (CI, Holm, MDD)
#   Table S4   Settlement duration: primary three-group and finer bands
#   Table S5   Root-node parameter-instability tests, all 15 trees
#   Table S6   Splits of every tree (alpha = .05)
#   Table S7   Terminal-node estimates and global age coefficients
#   Table S8   Sex and racialization contrasts within migration groups
#   Table S9   Between-group comparison of those contrasts
#   Table S10  All-available person-wave sensitivity analysis
#   (Table S11, the alpha = .01 comparison, is static LaTeX in the document.)
#
# SMALL CELLS. No count below 6 is written. White stratum sizes are never
# written (they would disclose missing racialization counts). Every depth-1
# node whose defining characteristic has a published total is checked for a
# back-calculable difference of 1-5; the script stops if one is found.
#
# Run from the project root:
#     Rscript Analysis/23_supplementary_tables.R
# Writes (local only until CLSA review):
#     Draft/manuscript_clsa_review_package/supplementary_results.tex (tables S1-S10
#       embedded between its GENERATED TABLES markers; the rest of the file is kept)
#     DataPrep/out/SUPPLEMENT_CHECKS.md
# ---------------------------------------------------------------------------

suppressPackageStartupMessages(library(partykit))
source("Analysis/era_gee_components.R")

OUT  <- "DataPrep/out"
PKG  <- "Draft/manuscript_clsa_review_package"
DATA <- "CLSA Datafiles for analysis"
Y    <- c("y_walk", "y_lsport", "y_msport", "y_ssport")
DOM  <- c("Walking", "Light", "Moderate", "Strenuous")
CMP  <- c("beta1", "beta2", "gamma", "delta")
BLK  <- c(beta1 = "Fitted Baseline levels ($\\beta_{1q}$)",
          beta2 = "Average change per wave ($\\beta_{2q}$)",
          gamma = "Age associations with Baseline levels ($\\gamma_q$)",
          delta = "Age-related differences in change ($\\delta_q$)")
BLKS <- c(beta1 = "Baseline levels", beta2 = "Change per wave",
          gamma = "Age and levels", delta = "Age and change")
DIG  <- c(beta1 = 3, beta2 = 3, gamma = 5, delta = 5)

balF <- readRDS(file.path(OUT, "analytic_long_balanced.rds"))
alls <- readRDS(file.path(OUT, "analytic_long_all.rds"))
raw  <- readRDS(file.path(OUT, "immigration_items_raw.rds"))
AGE_C <- mean(balF$z_age[balF$wave == 0])

# ---------------------------------------------------------------------------
# formatting
# ---------------------------------------------------------------------------
num <- function(x, d = 3) {
  s <- formatC(abs(x), format = "f", digits = d)
  ifelse(x < 0 & as.numeric(s) > 0, paste0("$-", s, "$"), s)
}
es  <- function(e, se, d = 3) paste0(num(e, d), " (", formatC(se, format = "f", digits = d), ")")
pv  <- function(p) ifelse(p < .001, "$< .001$", sub("^0", "", sprintf("%.3f", p)))
psci <- function(p) sapply(p, function(x) {
  if (x >= .001) return(sub("^0", "", sprintf("%.3f", x)))
  if (x <= 0) return("$< 10^{-300}$")
  e <- floor(log10(x)); m <- round(x / 10^e, 1)
  if (m >= 10) { m <- m / 10; e <- e + 1 }
  sprintf("$%.1f \\times 10^{%d}$", m, e)
})
W2  <- function(w) sprintf("%.2f", w)
Nm  <- function(n) gsub(",", "{,}", N(n), fixed = TRUE)          # counts inside $...$
pin <- function(p) ifelse(p < .001, "$p < .001$", paste0("$p = ", sub("^0", "", sprintf("%.3f", p)), "$"))
N   <- function(n) { if (n > 0 && n < 6) stop("count below 6 reached the output: ", n)
                     format(n, big.mark = ",", trim = TRUE) }

FRAG <- tempfile(fileext = ".tex")          # tables are written here, then embedded (end of script)
con <- file(FRAG, open = "wt", encoding = "UTF-8")
L   <- function(...) writeLines(paste0(...), con)
chk <- file(file.path(OUT, "SUPPLEMENT_CHECKS.md"), open = "wt", encoding = "UTF-8")
C   <- function(...) { s <- paste0(...); writeLines(s, chk); cat(s, "\n") }
C("# Supplement build checks"); C("")
C("**Generated:** ", format(Sys.time(), "%d %B %Y %H:%M"), " - `Analysis/23_supplementary_tables.R`"); C("")
C("Reference age: ", sprintf("%.4f", AGE_C)); C("")

L("% ---------------------------------------------------------------------------")
L("% Generated by Analysis/23_supplementary_tables.R on ", format(Sys.Date(), "%d %B %Y"), ".")
L("% Do not edit by hand: rerun the script instead.")
L("% ---------------------------------------------------------------------------")
L("")

# ---------------------------------------------------------------------------
# samples
# ---------------------------------------------------------------------------
add_grp <- function(d) {
  i  <- match(d$entity_id, raw$entity_id)
  fl <- raw$SDC_FIMM_COM[i]; yr <- suppressWarnings(as.numeric(raw$SDC_DRES_COM[i]))
  d$imm  <- ifelse(fl == "2", "Non-immigrant", ifelse(fl == "1", "Immigrant", NA))
  d$yrs  <- ifelse(!is.na(fl) & fl == "1" & !is.na(yr) & yr < 996, yr, NA)
  d$grp3 <- ifelse(d$imm == "Non-immigrant", "Non-immigrant",
            ifelse(!is.na(d$yrs), ifelse(d$yrs < 20, "Recent/mid-term", "Established"), NA))
  d$band <- ifelse(d$imm == "Non-immigrant", "Non-immigrant",
            ifelse(!is.na(d$yrs), as.character(cut(d$yrs, c(-Inf, 10, 20, 40, Inf), right = FALSE,
                                   labels = c("<10", "10-19", "20-39", ">=40"))), NA))
  d
}
bal   <- add_grp(balF); bal <- bal[!is.na(bal$imm), ]
allsD <- add_grp(alls); allsD <- allsD[!is.na(allsD$imm), ]
b0    <- bal[bal$wave == 0, ]
GRP3  <- c("Non-immigrant", "Recent/mid-term", "Established")
BAND  <- c("Non-immigrant", "<10", "10-19", "20-39", ">=40")
BANDL <- c("Non-immigrant" = "Non-immigrants", "<10" = "$<$10 years", "10-19" = "10--19 years",
           "20-39" = "20--39 years", ">=40" = "$\\geq$40 years")

C("## Samples"); C("")
C("- balanced, Flag-determinate: ", N(nrow(b0)), " persons, ", N(nrow(bal)), " person-waves")
C("- all-available, Flag-determinate: ", N(length(unique(allsD$id))), " persons, ", N(nrow(allsD)), " person-waves")
stopifnot(nrow(b0) == 24948, nrow(bal) == 74844, length(unique(allsD$id)) == 29169, nrow(allsD) == 81876)
stopifnot(!anyNA(bal$grp3), !anyNA(bal$band))
C("- groups: ", paste(sprintf("%s %s", names(table(b0$grp3)), sapply(table(b0$grp3), N)), collapse = ", "))
C("- bands: ", paste(sprintf("%s %s", names(table(b0$band)), sapply(table(b0$band), N)), collapse = ", "))
C("- median years in Canada (immigrants, balanced): ", median(b0$yrs, na.rm = TRUE),
  "; IQR ", paste(quantile(b0$yrs, c(.25, .75), na.rm = TRUE), collapse = "-"))

design  <- function(d, Ac = d$z_age - AGE_C) cbind(beta1 = 1, beta2 = d$X_time, gamma = Ac, delta = d$X_time * Ac)
fit_one <- function(d) era_gee_components(d[, Y], design(d), d$id)
nm_of   <- function(k) paste0(k, ":", Y)

# fb - fa for two independent fits
pair <- function(fa, fb) {
  nm <- rownames(fa$V); dif <- fb$theta - fa$theta; Vd <- fa$V + fb$V; se <- sqrt(diag(Vd))
  wald <- function(j) { j <- match(j, nm)
    W <- as.numeric(t(dif[j]) %*% solve(Vd[j, j, drop = FALSE]) %*% dif[j])
    c(W = W, df = length(j), p = pchisq(W, length(j), lower.tail = FALSE)) }
  names(dif) <- names(se) <- nm
  list(dif = dif, se = se, p = 2 * pnorm(-abs(dif / se)), mdd = 2.8 * se,
       block = sapply(CMP, function(k) wald(nm_of(k))), all = wald(nm))
}
# omnibus equality across K independent groups (all contrasts against group 1)
omnibus <- function(fits, comps) {
  ref <- fits[[1]]; oth <- fits[-1]; nm <- rownames(ref$V); j <- match(unlist(lapply(comps, nm_of)), nm)
  d  <- unlist(lapply(oth, function(f) (f$theta - ref$theta)[j]))
  k  <- length(oth); m <- length(j)
  V  <- matrix(0, k * m, k * m)
  for (a in seq_len(k)) for (b in seq_len(k)) {
    blk <- ref$V[j, j]; if (a == b) blk <- blk + oth[[a]]$V[j, j]
    V[(a - 1) * m + 1:m, (b - 1) * m + 1:m] <- blk
  }
  W <- as.numeric(t(d) %*% solve(V) %*% d)
  c(W = W, df = k * m, p = pchisq(W, k * m, lower.tail = FALSE))
}

# ===========================================================================
# Table S1 -- primary model, full sample
# ===========================================================================
f <- fit_one(bal)
tab_open <- function(caption, label, cols, size = "\\small", land = FALSE) {
  if (land) L("\\begin{landscape}")
  L("\\begin{table}[!ht]"); L("\\centering"); L("\\caption{", caption, "}"); L("\\label{", label, "}")
  L("\\begin{threeparttable}"); L(size); L("\\begin{tabular}{", cols, "}"); L("\\toprule")
}
tab_close <- function(note, land = FALSE) {
  L("\\bottomrule"); L("\\end{tabular}"); L("\\begin{tablenotes}"); L("\\footnotesize")
  L("\\item \\textit{Note}. ", note); L("\\end{tablenotes}"); L("\\end{threeparttable}"); L("\\end{table}")
  if (land) L("\\end{landscape}")
  L(""); L("\\clearpage"); L("")
}
dom_head <- function(first = "") L(first, " & ", paste(DOM, collapse = " & "), " \\\\")
# Long tables (S1, S4, S5, S6, S7): landscape longtable that continues onto the
# next page, with the header repeated and the note as the final row.
lt_open <- function(caption, label, cols, header, size = "footnotesize") {
  L("\\begin{landscape}"); L("\\begin{", size, "}"); L("\\begin{longtable}{", cols, "}")
  L("\\caption{", caption, "}\\label{", label, "} \\\\")
  L("\\toprule"); header(); L("\\midrule"); L("\\endfirsthead")
  L("\\toprule"); header(); L("\\midrule"); L("\\endhead")
  L("\\bottomrule"); L("\\endfoot")
}
lt_close <- function(note, ncol, width, size = "footnotesize") {
  L("\\multicolumn{", ncol, "}{p{", width, "}}{\\textit{Note}. ", note, "} \\\\")
  L("\\end{longtable}"); L("\\end{", size, "}"); L("\\end{landscape}"); L(""); L("\\clearpage"); L("")
}

lt_open("Full-Sample Estimates From the Primary Multivariate Longitudinal Model",
        "tab:S1", "lrrrr", function() dom_head())
L("\\multicolumn{5}{@{}l}{\\textit{A. Coefficients: estimate (SE)}} \\\\")
for (k in CMP) {
  L("\\addlinespace"); L("\\multicolumn{5}{@{}l}{", BLK[k], "} \\\\")
  L("\\quad Estimate (SE) & ", paste(es(f$B[k, ], f$SE[k, ], DIG[k]), collapse = " & "), " \\\\")
  L("\\quad 95\\% CI & ", paste(sprintf("[%s, %s]", num(f$B[k, ] - 1.96 * f$SE[k, ], DIG[k]),
                                        num(f$B[k, ] + 1.96 * f$SE[k, ], DIG[k])), collapse = " & "), " \\\\")
  L("\\quad $p$ & ", paste(pv(2 * pnorm(-abs(f$B[k, ] / f$SE[k, ]))), collapse = " & "), " \\\\")
}
# equal-change check: saturated wave means, contrast mu0 - 2 mu1 + mu2
Fs <- cbind(w1 = 1, w2 = as.numeric(bal$wave == 1), w3 = as.numeric(bal$wave == 2))
fs <- era_gee_components(bal[, Y], Fs, bal$id)
Lm <- matrix(0, 4, length(fs$theta)); colnames(Lm) <- rownames(fs$V)
for (j in seq_along(Y)) { Lm[j, paste0("w2:", Y[j])] <- -2; Lm[j, paste0("w3:", Y[j])] <- 1 }
dd_eq <- as.vector(Lm %*% fs$theta); Vd_eq <- Lm %*% fs$V %*% t(Lm)
W_eq <- as.numeric(t(dd_eq) %*% solve(Vd_eq) %*% dd_eq)
jt <- rbind(beta2 = era_wald(f, nm_of("beta2")), gamma = era_wald(f, nm_of("gamma")),
            delta = era_wald(f, nm_of("delta")))
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{B. Multivariate Wald tests across the four domains}} \\\\")
L("\\quad $\\beta_{2q} = 0$ for all $q$ & \\multicolumn{4}{l}{$\\chi^2(4) = ", W2(jt["beta2", "W"]), "$, ", pin((jt["beta2", "p"])), "} \\\\")
L("\\quad $\\gamma_{q} = 0$ for all $q$ & \\multicolumn{4}{l}{$\\chi^2(4) = ", W2(jt["gamma", "W"]), "$, ", pin((jt["gamma", "p"])), "} \\\\")
L("\\quad $\\delta_{q} = 0$ for all $q$ & \\multicolumn{4}{l}{$\\chi^2(4) = ", W2(jt["delta", "W"]), "$, ", pin((jt["delta", "p"])), "} \\\\")
L("\\quad Equal change across the two intervals & \\multicolumn{4}{l}{$\\chi^2(4) = ", W2(W_eq), "$, ",  pin((pchisq(W_eq, 4, lower.tail = FALSE))), "} \\\\")
# model-implied values at three ages
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{C. Model-implied values by baseline-visit age: estimate (SE)}} \\\\")
lin <- function(w) {                       # w: named weights on components -> est, se per domain
  t(sapply(seq_along(Y), function(q) {
    l <- setNames(rep(0, length(f$theta)), rownames(f$V))
    for (k in names(w)) l[paste0(k, ":", Y[q])] <- w[[k]]
    c(est = sum(l * f$theta), se = sqrt(as.numeric(t(l) %*% f$V %*% l)))
  }))
}
for (off in c(-10, 0, 10)) {
  lv <- lin(c(beta1 = 1, gamma = off)); ch <- lin(c(beta2 = 1, delta = off))
  L("\\addlinespace"); L("\\multicolumn{5}{@{}l}{Baseline-visit age ", sprintf("%.2f", AGE_C + off), " years} \\\\")
  L("\\quad Fitted Baseline level & ", paste(es(lv[, "est"], lv[, "se"]), collapse = " & "), " \\\\")
  L("\\quad Change per wave & ", paste(es(ch[, "est"], ch[, "se"]), collapse = " & "), " \\\\")
}
g20 <- lin(c(gamma = 20)); d20 <- lin(c(delta = 20))
L("\\addlinespace"); L("\\multicolumn{5}{@{}l}{Difference, ", sprintf("%.2f", AGE_C + 10), " minus ", sprintf("%.2f", AGE_C - 10), " years} \\\\")
L("\\quad Fitted Baseline level ($20\\gamma_q$) & ", paste(es(g20[, "est"], g20[, "se"]), collapse = " & "), " \\\\")
L("\\quad \\quad $p$ & ", paste(pv(2 * pnorm(-abs(g20[, "est"] / g20[, "se"]))), collapse = " & "), " \\\\")
L("\\quad Change per wave ($20\\delta_q$) & ", paste(es(d20[, "est"], d20[, "se"]), collapse = " & "), " \\\\")
L("\\quad \\quad $p$ & ", paste(pv(2 * pnorm(-abs(d20[, "est"] / d20[, "se"]))), collapse = " & "), " \\\\")
lt_close(ncol = 5, width = "18cm", paste0("$N = ", Nm(nrow(b0)), "$ participants (", N(nrow(bal)), " person-waves). Model: Equation~1 of the main text, ",
  "$Y_{itq} = \\beta_{1q} + \\beta_{2q} t + \\gamma_q A_i^{c} + \\delta_q (t \\times A_i^{c}) + \\varepsilon_{itq}$, with $t = 0, 1, 2$ ",
  "for Baseline, FU1, and FU2 and $A_i^{c}$ baseline-visit age centered at 62.15 years. Values are in scale points on the 1--4 response scale; ",
  "$\\gamma_q$ and $\\delta_q$ are per year of baseline-visit age. Standard errors are participant-clustered sandwich estimates. ",
  "Elementwise $p$ values are unadjusted two-sided Wald tests. The equal-change test compares the change from FU1 to FU2 with the change ",
  "from Baseline to FU1 in a model with separate means for the three assessments (Supplementary Table~S2)."))

C(""); C("## Table S1 cross-checks against the main text")
C("- beta1: ", paste(sprintf("%.3f", f$B["beta1", ]), collapse = ", "), "  (main text 3.060, 1.386, 1.224, 1.664)")
C("- beta2: ", paste(sprintf("%.3f", f$B["beta2", ]), collapse = ", "), "  (main text -0.066, 0.127, -0.013, -0.044)")
C("- joint gamma W = ", W2(jt["gamma", "W"]), " (main 610.44); joint delta W = ", W2(jt["delta", "W"]),
  " (main 108.11); equal change W = ", W2(W_eq), " (main 200.53)")
C("- 20*delta walking: ", sprintf("%.3f (%.3f)", d20[1, 1], d20[1, 2]), " (main -0.070, SE 0.009)")
C("- gamma strenuous per year: ", sprintf("%.4f (%.4f)", f$B["gamma", 4], f$SE["gamma", 4]), " (main -0.0145, SE 0.0006); 20*gamma = ", sprintf("%.3f", g20[4, 1]))
stopifnot(abs(W_eq - 200.53) < .01, abs(jt["delta", "W"] - 108.11) < .01, abs(jt["gamma", "W"] - 610.44) < .01)

# ===========================================================================
# Table S2 -- observed means; equal-change check by domain
# ===========================================================================
tab_open("Observed Means of the Four Physical-Activity Items at Each CLSA Assessment",
         "tab:S2", "lcccc")
L("Group & ", paste(DOM, collapse = " & "), " \\\\")
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{A. Observed means, Baseline / FU1 / FU2}} \\\\")
obs <- function(d) sapply(Y, function(q) paste(sprintf("%.2f", sapply(0:2, function(w) mean(d[[q]][d$wave == w]))), collapse = " / "))
groups_obs <- list("Full sample" = bal, "Non-immigrants" = bal[bal$imm == "Non-immigrant", ],
                   "Immigrants" = bal[bal$imm == "Immigrant", ],
                   "\\quad Recent/mid-term ($<$20 years)" = bal[bal$grp3 == "Recent/mid-term", ],
                   "\\quad Established ($\\geq$20 years)" = bal[bal$grp3 == "Established", ])
for (g in names(groups_obs)) {
  dg <- groups_obs[[g]]
  L(g, " ($n = ", Nm(length(unique(dg$id))), "$) & ", paste(obs(dg), collapse = " & "), " \\\\")
}
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{B. Full sample: difference between the two successive changes}} \\\\")
L("\\quad (FU2 $-$ FU1) $-$ (FU1 $-$ Baseline) & ", paste(es(dd_eq, sqrt(diag(Vd_eq))), collapse = " & "), " \\\\")
L("\\quad $p$ & ", paste(pv(2 * pnorm(-abs(dd_eq / sqrt(diag(Vd_eq))))), collapse = " & "), " \\\\")
L("\\quad Joint test across domains & \\multicolumn{4}{l}{$\\chi^2(4) = ", W2(W_eq), "$, ",  pin((pchisq(W_eq, 4, lower.tail = FALSE))), "} \\\\")
tab_close(paste0("Means are on the 1--4 response scale ($1 =$ never, $4 =$ often, 5--7 days) and are unadjusted for age. ",
  "Panel B is estimated in a model with a separate mean for each assessment, with participant-clustered sandwich standard errors. ",
  "A value of zero means that the change from FU1 to FU2 equalled the change from Baseline to FU1, which is the constraint implied by ",
  "summarizing change with a single coefficient per wave; negative values indicate that the second change was smaller (or more negative) ",
  "than the first."))

# ===========================================================================
# Table S3 -- immigrant vs non-immigrant
# ===========================================================================
fN <- fit_one(bal[bal$imm == "Non-immigrant", ]); fI <- fit_one(bal[bal$imm == "Immigrant", ])
pc <- pair(fN, fI); holm <- p.adjust(pc$p, "holm")
tab_open("Immigrant--Non-Immigrant Comparison: Elementwise Differences, Multiplicity Adjustment, and Detectable Differences",
         "tab:S3", "llrrrrrr", land = TRUE)
L("Parameter & Domain & Non-immigrants & Immigrants & Difference (SE) & 95\\% CI & $p$ / $p_{\\mathrm{Holm}}$ & Detectable \\\\")
L("\\midrule")
for (k in CMP) {
  L("\\multicolumn{8}{@{}l}{", BLK[k], "} \\\\")
  for (q in seq_along(Y)) {
    nmq <- paste0(k, ":", Y[q]); dg <- DIG[k]
    L("\\quad & ", DOM[q], " & ", es(fN$B[k, q], fN$SE[k, q], dg), " & ", es(fI$B[k, q], fI$SE[k, q], dg), " & ",
      es(pc$dif[nmq], pc$se[nmq], dg), " & [", num(pc$dif[nmq] - 1.96 * pc$se[nmq], dg), ", ",
      num(pc$dif[nmq] + 1.96 * pc$se[nmq], dg), "] & ", pv(pc$p[nmq]), " / ", pv(holm[nmq]), " & ",
      formatC(pc$mdd[nmq], format = "f", digits = dg), " \\\\")
  }
  L("\\quad & \\textit{Multivariate} & \\multicolumn{6}{l}{$\\chi^2(4) = ", W2(pc$block["W", k]), "$, ",    pin((pc$block["p", k])), "} \\\\")
  L("\\addlinespace")
}
L("\\multicolumn{2}{@{}l}{All 16 parameters} & \\multicolumn{6}{l}{$\\chi^2(16) = ", W2(pc$all["W"]), "$, ",  pin((pc$all["p"])), "} \\\\")
tab_close(paste0("$n = ", Nm(sum(b0$imm == "Non-immigrant")), "$ non-immigrants and $n = ", Nm(sum(b0$imm == "Immigrant")),
  "$ immigrants. The model was fitted separately in each group at the common reference age of 62.15 years. Differences are immigrant ",
  "minus non-immigrant. $p_{\\mathrm{Holm}}$ applies the Holm procedure across the 16 elementwise comparisons. ",
  "``Detectable'' is the difference detectable with 80\\% power in a two-sided test at $\\alpha = .05$, approximately $2.8 \\times SE$ of the difference. ",
  "Estimates, standard errors, and unadjusted $p$ values reproduce Table~2 of the main text."), land = TRUE)
C(""); C("## Table S3 cross-checks")
C("- block W: ", paste(sprintf("%s %.2f", CMP, pc$block["W", ]), collapse = ", "), "  (main 31.62, 13.70, 5.08, 0.95)")
C("- Holm < .05: ", paste(names(holm)[holm < .05], collapse = ", "))
stopifnot(all(abs(pc$block["W", ] - c(31.62, 13.70, 5.08, 0.95)) < .01),
          setequal(names(holm)[holm < .05], c("beta1:y_walk", "beta2:y_lsport")))

# ===========================================================================
# Table S4 -- settlement duration
# ===========================================================================
f3 <- lapply(setNames(GRP3, GRP3), function(g) fit_one(bal[bal$grp3 == g, ]))
p12 <- pair(f3[[1]], f3[[2]]); p13 <- pair(f3[[1]], f3[[3]]); p32 <- pair(f3[[3]], f3[[2]])
om3 <- sapply(CMP, function(k) omnibus(f3, k))
fb  <- lapply(setNames(BAND, BAND), function(g) fit_one(bal[bal$band == g, ]))
omB <- sapply(c("beta1", "beta2"), function(k) omnibus(fb[-1], k))         # equality across the four bands
omB5 <- sapply(c("beta1", "beta2"), function(k) omnibus(fb, k))             # bands and non-immigrants
desc <- function(g, col) { s <- b0[b0[[col]] == g, ]
  c(n = N(nrow(s)), age = sprintf("%.1f (%.1f)", mean(s$z_age), sd(s$z_age)),
    women = sprintf("%.1f", 100 * mean(s$z_sex == "Female"))) }

lt_open("Fitted Baseline Levels and Average Change per Wave by Settlement-Duration Group",
        "tab:S4", "lrrrr", function() L(" & ", paste(DOM, collapse = " & "), " \\\\"))
L("\\multicolumn{5}{@{}l}{\\textit{A. Primary classification}} \\\\")
G3L <- c("Non-immigrant" = "Non-immigrants", "Recent/mid-term" = "Recent/mid-term ($<$20 years)",
         "Established" = "Established ($\\geq$20 years)")
for (k in c("beta1", "beta2")) {
  L("\\addlinespace"); L("\\multicolumn{5}{@{}l}{", BLK[k], "} \\\\")
  for (g in GRP3) L("\\quad ", G3L[g], " & ", paste(es(f3[[g]]$B[k, ], f3[[g]]$SE[k, ]), collapse = " & "), " \\\\")
}
L("\\addlinespace")
L("\\multicolumn{5}{@{}l}{Multivariate tests: $p$ (4 df per pairwise test; 8 df omnibus)} \\\\")
L(" & Recent vs.\\ non-imm. & Established vs.\\ non-imm. & Recent vs.\\ established & Omnibus $\\chi^2(8)$ \\\\")
for (k in CMP) L("\\quad ", BLKS[k], " & ", pv(p12$block["p", k]), " & ", pv(p13$block["p", k]), " & ", pv(p32$block["p", k]),
                 " & ", W2(om3["W", k]), ", ", pin((om3["p", k])), " \\\\")
j2 <- nm_of("beta2")
L("\\quad Detectable change difference\\textsuperscript{a} & \\multicolumn{4}{l}{",
  paste(sprintf("%s %.3f", DOM, p12$mdd[j2]), collapse = "; "), "} \\\\")
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{B. Finer settlement-duration classification}} \\\\")
for (k in c("beta1", "beta2")) {
  L("\\addlinespace"); L("\\multicolumn{5}{@{}l}{", BLK[k], "} \\\\")
  for (g in BAND) L("\\quad ", BANDL[g], " & ", paste(es(fb[[g]]$B[k, ], fb[[g]]$SE[k, ]), collapse = " & "), " \\\\")
}
L("\\addlinespace")
L("\\multicolumn{5}{@{}l}{Omnibus tests of equality} \\\\")
for (k in c("beta1", "beta2"))
  L("\\quad ", BLKS[k], " & \\multicolumn{4}{p{10.5cm}}{Four immigrant groups: $\\chi^2(12) = ", W2(omB["W", k]), "$, ",    pin((omB["p", k])), "; with non-immigrants: $\\chi^2(16) = ", W2(omB5["W", k]), "$, ",    pin((omB5["p", k])), "} \\\\")
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{C. Group characteristics}} \\\\")
L(" & $n$ & Age, $M$ ($SD$) & Women, \\% & \\\\")
for (g in GRP3) { x <- desc(g, "grp3"); L("\\quad ", G3L[g], " & ", x["n"], " & ", x["age"], " & ", x["women"], " & \\\\") }
for (g in BAND[-1]) { x <- desc(g, "band"); L("\\quad ", BANDL[g], " & ", x["n"], " & ", x["age"], " & ", x["women"], " & \\\\") }
lt_close(ncol = 5, width = "17cm", paste0("Estimate (SE) in scale points at the common reference baseline-visit age of 62.15 years; the model was fitted separately ",
  "in each group. Settlement duration is years in Canada at the CLSA baseline visit. Pairwise tests use 4 df per parameter block; the ",
  "three-group omnibus test evaluates both contrasts against non-immigrants jointly (8 df). $p$ values are unadjusted. ",
  "\\textsuperscript{a}Difference in average change per wave between recent/mid-term immigrants and non-immigrants detectable with 80\\% ",
  "power in a two-sided test at $\\alpha = .05$ ($\\approx 2.8 \\times SE$ of the difference). ",
  "Recent/mid-term and $<$10-year immigrants were considerably younger than the reference age, so their fitted values at 62.15 years ",
  "rely on the within-group age terms of the model. Median years in Canada among immigrants was ", median(b0$yrs), "."))
C(""); C("## Table S4 cross-checks")
C("- primary pairwise beta1 p: recent-non ", pv(p12$block["p", "beta1"]), ", estab-non ", pv(p13$block["p", "beta1"]),
  ", recent-estab ", pv(p32$block["p", "beta1"]), "  (main .852, <.001, .220)")
C("- primary pairwise beta2 p: recent-non ", pv(p12$block["p", "beta2"]), ", estab-non ", pv(p13$block["p", "beta2"]),
  ", recent-estab ", pv(p32$block["p", "beta2"]), "; omnibus W ", W2(om3["W", "beta2"]), " p ", pv(om3["p", "beta2"]),
  "  (main .385, .022, .544; 15.45, .051)")
C("- detectable change differences recent vs non: ", paste(sprintf("%.3f", p12$mdd[j2]), collapse = ", "), "  (main 0.065-0.139)")
C("- bands omnibus (4 immigrant groups): beta1 W ", W2(omB["W", "beta1"]), " p ", pv(omB["p", "beta1"]),
  "; beta2 W ", W2(omB["W", "beta2"]), " p ", pv(omB["p", "beta2"]))
stopifnot(abs(om3["W", "beta2"] - 15.45) < .01, all(abs(range(p12$mdd[j2]) - c(.065, .139)) < .0006))

# ===========================================================================
# Partitioning trees
# ===========================================================================
m05 <- readRDS(file.path(OUT, "_mob_final_model.rds"))
t3  <- readRDS(file.path(OUT, "_three_group.rds"))$mob
fl_all <- raw$SDC_FIMM_COM[match(balF$entity_id, raw$entity_id)]
bal19  <- add_grp(balF); bal19 <- bal19[!is.na(bal19$grp3), ]
# hide_n: node sizes of the recent/mid-term trees are not written. Combined with
# the published group total (482) and racialized total (195), the root and the
# racialization nodes would let a count below 6 be derived (build log, 17 Sep 2026).
SAMPLES <- list(
  list(key = "D1", lab = "Full sample", data = balF, trees = m05, pre = "D1 ", pop = "full", hide_n = FALSE),
  list(key = "D2", lab = "Immigrants only (settlement duration as candidate)",
       data = balF[!is.na(fl_all) & fl_all == "1", ], trees = m05, pre = "D2 ", pop = "imm", hide_n = FALSE),
  list(key = "NI", lab = "Non-immigrants", data = bal19[bal19$grp3 == "Non-immigrant", ], trees = t3,
       pre = "Non-immigrant ", pop = "non", hide_n = FALSE),
  list(key = "RM", lab = "Recent/mid-term immigrants", data = bal19[bal19$grp3 == "Recent/mid-term", ], trees = t3,
       pre = "Recent/mid-term ", pop = "recent", hide_n = TRUE),
  list(key = "ES", lab = "Established immigrants", data = bal19[bal19$grp3 == "Established", ], trees = t3,
       pre = "Established ", pop = "estab", hide_n = FALSE))
NN <- function(n, s) if (isTRUE(s$hide_n)) "--" else N(n)
HIDE_NOTE <- paste0("Node sizes are not shown for the recent/mid-term trees because, combined with totals reported elsewhere, ",
                    "they would allow counts below six to be derived; every node in those trees contained at least 100 participants.")
DIAG  <- c(joint = "joint", level = "intercept", change = "slope")
DIAGL <- c(joint = "Joint", level = "Level", change = "Change")
ZL <- c(z_imm_flag = "Immigrant status", z_duration = "Settlement duration", z_sex = "Sex",
        z_racialized = "Racialization", z_educ4 = "Education", z_incneeds = "Income adequacy", z_own = "Housing tenure")
ZS <- c(z_imm_flag = "Imm", z_duration = "Dur", z_sex = "Sex", z_racialized = "Rac", z_educ4 = "Edu",
        z_incneeds = "Inc", z_own = "Ten")

lev_lab <- function(vn, lv, all_lv) {
  if (vn %in% c("z_educ4", "z_incneeds")) {
    pos <- match(lv, all_lv); pre <- if (vn == "z_educ4") "E" else "I"
    if (length(pos) > 1 && all(diff(sort(pos)) == 1)) return(sprintf("%s%d--%s%d", pre, min(pos), pre, max(pos)))
    return(paste(sprintf("%s%d", pre, sort(pos)), collapse = ","))
  }
  map <- c(Female = "women", Male = "men", White = "White", Racialized = "racialized",
           `Non-immigrant` = "non-immigrant", Immigrant = "immigrant", `Long-term` = "$\\geq$20 y",
           `Recent/mid-term` = "$<$20 y", Own = "own", Rent = "rent", Other = "other")
  paste(map[lv], collapse = "/")
}
tree_info <- function(fit, dd) {
  tr <- fit$tree
  stopifnot(length(fit$node) == nrow(dd))
  pid <- function(ids) length(unique(dd$id[!is.na(fit$node) & fit$node %in% ids]))
  paths <- list()
  walk <- function(nd, conds) {
    paths[[as.character(id_node(nd))]] <<- conds
    if (is.terminal(nd)) return(invisible())
    sp <- split_node(nd); vn <- names(tr$data)[varid_split(sp)]; zz <- tr$data[[vn]]; idx <- index_split(sp)
    kd <- kids_node(nd)
    for (k in seq_along(kd)) { cc <- conds; cc[[vn]] <- levels(zz)[which(idx == k)]; walk(kd[[k]], cc) }
  }
  walk(node_party(tr), list())
  path_lab <- function(id) { cc <- paths[[as.character(id)]]
    if (!length(cc)) return("All")
    paste(sapply(names(cc), function(v) lev_lab(v, cc[[v]], levels(tr$data[[v]]))), collapse = "; ") }
  root <- nodeapply(tr, 1, function(n) info_node(n))[[1]]
  inner <- setdiff(nodeids(tr), nodeids(tr, terminal = TRUE))
  splits <- lapply(inner, function(i) {
    nd <- nodeapply(tr, i, identity)[[1]]; sp <- split_node(nd); vn <- names(tr$data)[varid_split(sp)]
    zz <- tr$data[[vn]]; idx <- index_split(sp); ti <- info_node(nd)
    list(id = i, path = path_lab(i), n = pid(nodeids(tr, from = i, terminal = TRUE)), var = vn,
         left = lev_lab(vn, levels(zz)[which(idx == 1)], levels(zz)), right = lev_lab(vn, levels(zz)[which(idx == 2)], levels(zz)),
         p = ti$test["p.value", vn], stat = ti$test["statistic", vn])
  })
  # terminal-node estimates on the age-adjusted outcomes
  Ac <- dd$z_age - AGE_C
  off <- sapply(seq_along(Y), function(q) fit$gamma["age", q] * Ac + fit$gamma["age_time", q] * dd$X_time * Ac)
  term <- lapply(nodeids(tr, terminal = TRUE), function(i) {
    ix <- which(!is.na(fit$node) & fit$node == i)
    m <- era_gee_components(as.matrix(dd[ix, Y]) - off[ix, , drop = FALSE], cbind(beta1 = 1, beta2 = dd$X_time[ix]), dd$id[ix])
    list(id = i, path = path_lab(i), n = length(unique(dd$id[ix])), B = m$B)
  })
  list(root = root, root_n = pid(nodeids(tr, terminal = TRUE)), splits = splits, term = term,
       gamma = fit$gamma, width = width(tr), paths = paths, conv = fit$converged, tr = tr,
       node = fit$node, ids = dd$id)
}
TI <- list()
for (s in SAMPLES) for (dg in names(DIAG)) {
  key <- paste0(s$pre, DIAG[dg]); fit <- s$trees[[key]]
  if (is.null(fit)) stop("missing fit: ", key)
  TI[[paste(s$key, dg)]] <- c(tree_info(fit, s$data), list(sample = s, diag = dg))
}

# ---- small-cell guard: depth-1 nodes vs published totals -----------------
# Published totals: Table 1 (full sample, non-immigrants, immigrants: sex,
# education, income adequacy, racialization) and the racialized n of each
# migration group (Figure 3 caption). Depth-1 node n is compared with the
# number of participants in the tree population having that characteristic.
C(""); C("## Small-cell guard (depth-1 nodes against published totals)")
b0$z_imm_flag <- ifelse(b0$imm == "Immigrant", "Immigrant", "Non-immigrant")
popdat <- function(pop) switch(pop, full = b0, imm = b0[b0$imm == "Immigrant", ], non = b0[b0$imm == "Non-immigrant", ],
                               recent = b0[b0$grp3 == "Recent/mid-term", ], estab = b0[b0$grp3 == "Established", ])
# Table 1 publishes sex, education, income adequacy, racialization, and tenure
# for the full sample and both immigrant-status groups; Supplementary Table S8
# publishes sex (women/men) and racialized n for each migration group.
published_vars <- function(pop) if (pop %in% c("full", "imm", "non"))
  c("z_sex", "z_educ4", "z_incneeds", "z_racialized", "z_own", "z_imm_flag") else c("z_sex", "z_racialized")
bad  <- function(x) x > 0 && x < 6
flag <- 0
for (k in names(TI)) {
  ti <- TI[[k]]; pop <- ti$sample$pop; P <- popdat(pop); hid <- isTRUE(ti$sample$hide_n)
  g_all <- nrow(P) - ti$root_n
  C("- ", k, if (hid) " [node sizes hidden]" else "", ": root n ", N(ti$root_n), " of ", N(nrow(P)),
    " (missing on a candidate: ", g_all, ")")
  if (bad(g_all)) { C("  **FLAG** root gap below 6"); if (!hid) flag <- flag + 1 }
  for (sp in ti$splits) {
    if (length(ti$paths[[as.character(sp$id)]])) next      # only the root split defines depth-1 nodes
    if (!(sp$var %in% published_vars(pop))) next
    for (side in 1:2) {
      kid   <- kids_node(nodeapply(ti$tr, sp$id, identity)[[1]])[[side]]
      lv    <- ti$paths[[as.character(id_node(kid))]][[sp$var]]
      kid_n <- length(unique(ti$ids[!is.na(ti$node) & ti$node %in% nodeids(ti$tr, from = id_node(kid), terminal = TRUE)]))
      g_side <- sum(P[[sp$var]] %in% lv) - kid_n            # this side, missing on another candidate
      g_rest <- g_all - g_side                              # everyone else missing on a candidate
      C("  - depth-1 ", sp$var, " {", paste(lv, collapse = ","), "}: node n ", N(kid_n),
        "; derivable gaps ", g_side, " (this side) and ", g_rest, " (remainder)")
      if (bad(g_side) || bad(g_rest)) { C("    **FLAG** back-calculable count below 6", if (hid) " -- sizes hidden, not written" else "")
        if (!hid) flag <- flag + 1 }
    }
  }
}
if (flag) stop(flag, " small-cell flag(s) in written tables; see ", file.path(OUT, "SUPPLEMENT_CHECKS.md"))
C("- no flags in written tables")

# ===========================================================================
# Table S5 -- root-node instability tests
# ===========================================================================
lt_open("Root-Node Parameter-Instability Tests for All Partitioning Trees", "tab:S5", "lrrrrrr", function() {
  L(" & \\multicolumn{2}{c}{Joint diagnostic} & \\multicolumn{2}{c}{Level diagnostic} & \\multicolumn{2}{c}{Change diagnostic} \\\\")
  L("\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}")
  L("Candidate partitioning variable & Statistic & Adjusted $p$ & Statistic & Adjusted $p$ & Statistic & Adjusted $p$ \\\\")
})
for (s in SAMPLES) {
  if (s$key != SAMPLES[[1]]$key) L("\\midrule")
  L("\\multicolumn{7}{@{}l}{\\textit{", s$lab, "} (", if (isTRUE(s$hide_n)) "node sizes not shown" else
    paste0("$n = ", Nm(TI[[paste(s$key, "joint")]]$root_n), "$"), ")} \\\\")
  zv <- colnames(TI[[paste(s$key, "joint")]]$root$test)
  ord <- order(TI[[paste(s$key, "joint")]]$root$test["p.value", ])
  for (v in zv[ord]) {
    cells <- unlist(lapply(names(DIAG), function(dg) { tt <- TI[[paste(s$key, dg)]]$root$test
      c(sprintf("%.2f", tt["statistic", v]), psci(tt["p.value", v])) }))
    L("\\quad ", ZL[v], " & ", paste(cells, collapse = " & "), " \\\\")
  }
  L("\\quad Terminal nodes & \\multicolumn{2}{r}{", TI[[paste(s$key, "joint")]]$width, "} & \\multicolumn{2}{r}{",
    TI[[paste(s$key, "level")]]$width, "} & \\multicolumn{2}{r}{", TI[[paste(s$key, "change")]]$width, "} \\\\")
}
lt_close(ncol = 7, width = "17.5cm", paste0("Statistics are score-based parameter-instability tests at the root node of each tree; $p$ values are ",
  "Bonferroni-adjusted over the candidate variables of that tree. The joint diagnostic tests the eight node-specific parameters ",
  "(four fitted Baseline levels and four average changes per wave), the level diagnostic the four fitted Baseline levels, and the change ",
  "diagnostic the four change parameters after adjustment for variation attributable to level differences (Supplementary Methods S5). ",
  "Baseline-visit age and its interaction with wave were estimated globally in every tree and were not candidates. $n$ is the number of ",
  "participants with observed values on all candidate variables of that tree. Within each block, candidates are ordered by the joint-diagnostic ",
  "$p$ value. Trees were grown with test-based pre-pruning at $\\alpha = .05$, a minimum node size of 100 participants, and a maximum depth of 4. ",
  HIDE_NOTE))

C(""); C("## Table S5 cross-checks (Table 3 of the main text)")
rt <- TI[["D1 joint"]]$root$test; rl <- TI[["D1 level"]]$root$test; rc <- TI[["D1 change"]]$root$test
for (v in colnames(rt)) C("- ", v, ": ", psci(rt["p.value", v]), " | ", psci(rl["p.value", v]), " | ", psci(rc["p.value", v]))
C("- non-immigrant racialization root p (joint/level/change): ",
  paste(sapply(c("joint", "level", "change"), function(dg) sprintf("%.3f", TI[[paste("NI", dg)]]$root$test["p.value", "z_racialized"])), collapse = " / "),
  "  (earlier draft .887/.990/.986)")
C("- settlement duration root p in immigrants-only trees (joint/level/change): ",
  paste(sapply(c("joint", "level", "change"), function(dg) sprintf("%.3f", TI[[paste("D2", dg)]]$root$test["p.value", "z_duration"])), collapse = " / "),
  "  (earlier draft .140/.026/.992)")

# ===========================================================================
# Table S6 -- splits
# ===========================================================================
L("\\begin{footnotesize}")
L("\\begin{longtable}{p{0.5cm}p{5.0cm}rp{1.9cm}p{3.0cm}r}")
L("\\caption{Splits of Every Partitioning Tree at the Primary Threshold ($\\alpha = .05$)}\\label{tab:S6} \\\\")
L("\\toprule")
L("Node & Subgroup defined by earlier splits & $n$ & Split variable & Partition (left $|$ right) & Adjusted $p$ \\\\")
L("\\midrule"); L("\\endfirsthead")
L("\\toprule")
L("Node & Subgroup defined by earlier splits & $n$ & Split variable & Partition (left $|$ right) & Adjusted $p$ \\\\")
L("\\midrule"); L("\\endhead")
L("\\bottomrule"); L("\\endfoot")
for (s in SAMPLES) for (dg in names(DIAG)) {
  ti <- TI[[paste(s$key, dg)]]
  L("\\multicolumn{6}{@{}l}{\\textit{", s$lab, ", ", tolower(DIAGL[dg]), " diagnostic} (", ti$width, " terminal node",
    if (ti$width > 1) "s" else "", ")} \\\\")
  if (!length(ti$splits)) { L(" & No split & ", NN(ti$root_n, s), " & & & \\\\"); L("\\addlinespace"); next }
  for (sp in ti$splits)
    L(sp$id, " & ", sp$path, " & ", NN(sp$n, s), " & ", ZL[sp$var], " & ", sp$left, " $|$ ", sp$right, " & ", psci(sp$p), " \\\\")
  L("\\addlinespace")
}
L("\\multicolumn{6}{p{15cm}}{\\textit{Note}. Node numbers follow the depth-first numbering of the fitted tree. $n$ is the number of ",
  "participants in the node. $p$ is the Bonferroni-adjusted instability-test $p$ value of the selected variable in that node. ",
  "Codes: I1 = income meets needs very well, I2 = adequately, I3 = with some difficulty, I4 = not very well, I5 = totally inadequately; ",
  "E1 = less than secondary, E2 = secondary without post-secondary, E3 = some post-secondary, E4 = post-secondary degree or diploma; ",
  "$<$20 y and $\\geq$20 y = years in Canada. Housing tenure: own versus rent/other. ", HIDE_NOTE, "} \\\\")
L("\\end{longtable}")
L("\\end{footnotesize}")
L(""); L("\\clearpage"); L("")

# ===========================================================================
# Table S7 -- terminal nodes
# ===========================================================================
L("\\begin{landscape}")
L("\\begin{footnotesize}")
L("\\begin{longtable}{p{0.5cm}p{6.0cm}rrrrrrrrr}")
L("\\caption{Terminal-Node Estimates and Global Age Coefficients of Every Partitioning Tree}\\label{tab:S7} \\\\")
hdr <- function() {
  L("\\toprule")
  L(" & & & \\multicolumn{4}{c}{Fitted Baseline level ($\\beta_{1q}$)} & \\multicolumn{4}{c}{Average change per wave ($\\beta_{2q}$)} \\\\")
  L("\\cmidrule(lr){4-7}\\cmidrule(lr){8-11}")
  L("Node & Subgroup & $n$ & Walk & Light & Mod. & Stren. & Walk & Light & Mod. & Stren. \\\\")
  L("\\midrule")
}
hdr(); L("\\endfirsthead"); hdr(); L("\\endhead"); L("\\bottomrule"); L("\\endfoot")
for (s in SAMPLES) for (dg in names(DIAG)) {
  ti <- TI[[paste(s$key, dg)]]
  L("\\multicolumn{11}{@{}l}{\\textit{", s$lab, ", ", tolower(DIAGL[dg]), " diagnostic}} \\\\")
  for (tt in ti$term)
    L(tt$id, " & ", tt$path, " & ", NN(tt$n, s), " & ", paste(num(tt$B["beta1", ]), collapse = " & "), " & ",
      paste(num(tt$B["beta2", ]), collapse = " & "), " \\\\")
  L(" & \\quad Global $\\gamma_q$ / $\\delta_q$ (per year) & & ", paste(num(ti$gamma["age", ], 5), collapse = " & "), " & ",
    paste(num(ti$gamma["age_time", ], 5), collapse = " & "), " \\\\")
  L("\\addlinespace")
}
L("\\multicolumn{11}{p{21cm}}{\\textit{Note}. Node-specific fitted Baseline levels and average changes per wave are in scale points at the ",
  "reference baseline-visit age of 62.15 years, estimated within each terminal node after removing the global age terms. The row labelled ",
  "Global $\\gamma_q$ / $\\delta_q$ gives, under the Baseline-level columns, the age association with Baseline levels and, under the ",
  "change columns, the age-related difference in change, both per year of baseline-visit age and common to all nodes of that tree. ",
  "Trees with a single terminal node show the root estimates. Subgroup codes as in Supplementary Table~S6. Standard errors are not shown ",
  "because node-level estimates condition on the data-driven partition and on the estimated global age coefficients. ", HIDE_NOTE, "} \\\\")
L("\\end{longtable}")
L("\\end{footnotesize}")
L("\\end{landscape}")
L(""); L("\\clearpage"); L("")

C(""); C("## Table S7 cross-checks (Table 3 change-tree nodes)")
for (tt in TI[["D1 change"]]$term) C("- node ", tt$id, " (", tt$path, ", n ", N(tt$n), "): b2 ",
                                     paste(sprintf("%.3f", tt$B["beta2", ]), collapse = ", "))
C("  (main: women 12,652 -0.065 0.156 -0.006 -0.040; non-imm men 9,756 -0.065 0.087 -0.021 -0.051; imm men 2,272 -0.076 0.135 -0.020 -0.029)")

# ===========================================================================
# Tables S8, S9 -- stratified contrasts and their between-group comparison
# ===========================================================================
STRAT <- list(sex = c(v = "z_sex", l1 = "Female", l2 = "Male"),
              rac = c(v = "z_racialized", l1 = "White", l2 = "Racialized"))
POPS  <- list("Non-immigrants" = bal$grp3 == "Non-immigrant", "Recent/mid-term" = bal$grp3 == "Recent/mid-term",
              "Established" = bal$grp3 == "Established", "Immigrants (pooled)" = bal$imm == "Immigrant")
SC <- list()
for (sn in names(STRAT)) for (pp in names(POPS)) {
  st <- STRAT[[sn]]; inpop <- POPS[[pp]] & !is.na(bal[[st["v"]]])
  d1 <- bal[inpop & bal[[st["v"]]] == st["l1"], ]; d2 <- bal[inpop & bal[[st["v"]]] == st["l2"], ]
  f1 <- fit_one(d1); f2 <- fit_one(d2)
  SC[[paste(sn, pp)]] <- list(f1 = f1, f2 = f2, pc = pair(f1, f2), n1 = length(unique(d1$id)), n2 = length(unique(d2$id)))
}
tab_open("Sex and Racialization Contrasts Within Migration Groups", "tab:S8", "llrrrr", size = "\\footnotesize", land = TRUE)
L("Contrast and group & Parameter & Walking & Light & Moderate & Strenuous \\\\")
L("\\midrule")
SNL <- c(sex = "Men minus women", rac = "Racialized minus White")
for (sn in names(STRAT)) {
  L("\\multicolumn{6}{@{}l}{\\textit{", SNL[sn], "}} \\\\")
  for (pp in names(POPS)[1:3]) {
    sc <- SC[[paste(sn, pp)]]; pc2 <- sc$pc
    nlab <- if (sn == "sex") sprintf("women $n = %s$, men $n = %s$", Nm(sc$n1), Nm(sc$n2)) else sprintf("racialized $n = %s$", Nm(sc$n2))
    L("\\multicolumn{6}{@{}l}{\\quad ", pp, " (", nlab, ")} \\\\")
    L("\\quad & ", BLKS["beta1"], " & ", paste(es(pc2$dif[nm_of("beta1")], pc2$se[nm_of("beta1")]), collapse = " & "), " \\\\")
    L("\\quad & ", BLKS["beta2"], " & ", paste(es(pc2$dif[nm_of("beta2")], pc2$se[nm_of("beta2")]), collapse = " & "), " \\\\")
    L("\\quad & Multivariate tests & \\multicolumn{4}{p{13cm}}{", paste(sprintf("%s: $\\chi^2(4) = %s$, %s", BLKS, W2(pc2$block["W", ]),
                                                              pin((pc2$block["p", ]))), collapse = "; "), "} \\\\")
    L("\\addlinespace")
  }
}
tab_close(paste0("Estimate (SE) of the contrast in scale points at the reference baseline-visit age of 62.15 years. The model was fitted ",
  "separately in each stratum of each migration group, so each contrast is estimated identically in every group and does not depend on the ",
  "partitioning trees. Multivariate tests use 4 df per parameter block; $p$ values are unadjusted. Sex refers to the baseline sex item ",
  "(female/male); for readability, female and male participants are referred to as women and men. Sizes of the White strata are not reported ",
  "because, together with published totals, they would allow counts below six to be derived."), land = TRUE)

tab_open("Between-Group Comparisons of the Sex and Racialization Contrasts", "tab:S9", "llrrrr", size = "\\footnotesize", land = TRUE)
L("Comparison & Parameter & Walking & Light & Moderate & Strenuous \\\\")
L("\\midrule")
S9 <- list()
for (sn in names(STRAT)) {
  L("\\multicolumn{6}{@{}l}{\\textit{", SNL[sn], ": difference between migration groups}} \\\\")
  ref <- SC[[paste(sn, "Non-immigrants")]]
  for (pp in c("Recent/mid-term", "Established", "Immigrants (pooled)")) {
    oth <- SC[[paste(sn, pp)]]
    D <- oth$pc$dif - ref$pc$dif; VD <- oth$f1$V + oth$f2$V + ref$f1$V + ref$f2$V; se <- sqrt(diag(VD))
    blk <- sapply(CMP, function(k) { j <- match(nm_of(k), names(D))
      W <- as.numeric(t(D[j]) %*% solve(VD[j, j]) %*% D[j]); c(W = W, p = pchisq(W, 4, lower.tail = FALSE)) })
    S9[[paste(sn, pp)]] <- blk
    L("\\multicolumn{6}{@{}l}{\\quad ", pp, " vs.\\ non-immigrants} \\\\")
    L("\\quad & ", BLKS["beta1"], " & ", paste(es(D[nm_of("beta1")], se[nm_of("beta1")]), collapse = " & "), " \\\\")
    L("\\quad & ", BLKS["beta2"], " & ", paste(es(D[nm_of("beta2")], se[nm_of("beta2")]), collapse = " & "), " \\\\")
    L("\\quad & Multivariate tests & \\multicolumn{4}{p{13cm}}{", paste(sprintf("%s: $\\chi^2(4) = %s$, %s", BLKS, W2(blk["W", ]),
                                                              pin((blk["p", ]))), collapse = "; "), "} \\\\")
    L("\\addlinespace")
  }
}
tab_close(paste0("Each entry is the within-group contrast (Supplementary Table~S8) in the named immigrant group minus the same contrast among ",
  "non-immigrants, in scale points at the reference baseline-visit age of 62.15 years. Groups and strata are disjoint, so the variance of each ",
  "difference is the sum of the four stratum variances. ``Immigrants (pooled)'' combines the recent/mid-term and established groups. ",
  "Multivariate tests use 4 df per parameter block; $p$ values are unadjusted."), land = TRUE)

C(""); C("## Tables S8-S9 cross-checks")
C("- racialized-White beta1 block p by group: ", paste(sapply(names(POPS)[1:3], function(pp) pv(SC[[paste("rac", pp)]]$pc$block["p", "beta1"])), collapse = ", "),
  "  (main: n.s. / .037 / <.001)")
C("- racialized-White beta2 block p by group: ", paste(sapply(names(POPS)[1:3], function(pp) pv(SC[[paste("rac", pp)]]$pc$block["p", "beta2"])), collapse = ", "),
  "  (earlier draft .814/.337/.168)")
C("- racialized-White walking beta1: ", paste(sapply(names(POPS)[1:3], function(pp) sprintf("%.3f", SC[[paste("rac", pp)]]$pc$dif["beta1:y_walk"])), collapse = ", "),
  "  (earlier draft +0.014/-0.360/-0.260)")
C("- racialized n: ", paste(sapply(names(POPS)[1:3], function(pp) N(SC[[paste("rac", pp)]]$n2)), collapse = ", "), "  (Figure 3: 457/195/628)")
C("- men-women beta2 block p by group: ", paste(sapply(names(POPS)[1:3], function(pp) pv(SC[[paste("sex", pp)]]$pc$block["p", "beta2"])), collapse = ", "),
  "  (main <.001/.138/.039 for non/recent/established)")
C("- men-women light beta2 contrast: ", paste(sapply(names(POPS)[1:3], function(pp) sprintf("%.3f", SC[[paste("sex", pp)]]$pc$dif["beta2:y_lsport"])), collapse = ", "))
C("- difference-of-contrasts, racialization beta1 W: recent ", W2(S9[["rac Recent/mid-term"]]["W", "beta1"]),
  " p ", pv(S9[["rac Recent/mid-term"]]["p", "beta1"]), "; established ", W2(S9[["rac Established"]]["W", "beta1"]),
  " p ", pv(S9[["rac Established"]]["p", "beta1"]), "; pooled ", W2(S9[["rac Immigrants (pooled)"]]["W", "beta1"]),
  " p ", pv(S9[["rac Immigrants (pooled)"]]["p", "beta1"]), "  (main 8.53/.074; 16.54/.002; 18.93/<.001)")
stopifnot(abs(S9[["rac Immigrants (pooled)"]]["W", "beta1"] - 18.93) < .01,
          all(sapply(names(POPS)[1:3], function(pp) SC[[paste("rac", pp)]]$n2) == c(457, 195, 628)))

# ===========================================================================
# Table S10 -- all-available person-wave sensitivity analysis
# ===========================================================================
fA  <- fit_one(allsD)
fAN <- fit_one(allsD[allsD$imm == "Non-immigrant", ]); fAI <- fit_one(allsD[allsD$imm == "Immigrant", ])
pA  <- pair(fAN, fAI)
jtA <- rbind(beta2 = era_wald(fA, nm_of("beta2")), gamma = era_wald(fA, nm_of("gamma")), delta = era_wald(fA, nm_of("delta")))
pers <- allsD[!duplicated(allsD$id), c("id", "imm")]
nw   <- tapply(allsD$wave, allsD$id, length); pers$k <- nw[as.character(pers$id)]
# retention as defined in the main text: balanced participants as a share of all
# baseline Comprehensive participants in the same Immigration-Flag group. The
# cohort denominators are NOT written: with the published cohort total (30,097)
# they would disclose the number of participants without a determinate Flag.
coh  <- table(raw$SDC_FIMM_COM[!duplicated(raw$entity_id)])
ret  <- sapply(c("Non-immigrant", "Immigrant"), function(g) { k <- pers$k[pers$imm == g]
  c(n = length(k), pw = sum(allsD$imm == g), k1 = mean(k == 1), k2 = mean(k == 2), k3 = mean(k == 3),
    retained = sum(b0$imm == g) / as.numeric(coh[if (g == "Immigrant") "1" else "2"])) })
tab_open("Sensitivity Analysis Using All Available Complete Person-Wave Records", "tab:S10", "lrrrr", size = "\\footnotesize")
L(" & ", paste(DOM, collapse = " & "), " \\\\")
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{A. Primary longitudinal model, all-available sample: estimate (SE)}} \\\\")
for (k in CMP) L("\\quad ", BLKS[k], " & ", paste(es(fA$B[k, ], fA$SE[k, ], DIG[k]), collapse = " & "), " \\\\")
for (k in c("beta2", "gamma", "delta"))
  L("\\quad Joint test, ", BLKS[k], " & \\multicolumn{4}{l}{$\\chi^2(4) = ", W2(jtA[k, "W"]), "$, ", pin((jtA[k, "p"])), "} \\\\")
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{B. Immigrant minus non-immigrant, all-available sample: estimate (SE)}} \\\\")
for (k in CMP) L("\\quad ", BLKS[k], " & ", paste(es(pA$dif[nm_of(k)], pA$se[nm_of(k)], DIG[k]), collapse = " & "), " \\\\")
L("\\addlinespace")
L("\\multicolumn{5}{@{}l}{Multivariate tests: balanced sample vs.\\ all-available sample} \\\\")
for (k in CMP) L("\\quad ", BLKS[k], " & \\multicolumn{4}{l}{$\\chi^2(4) = ", W2(pc$block["W", k]), "$, ", pin((pc$block["p", k])),
                 " \\quad vs.\\quad $\\chi^2(4) = ", W2(pA$block["W", k]), "$, ", pin((pA$block["p", k])), "} \\\\")
L("\\midrule")
L("\\multicolumn{5}{@{}l}{\\textit{C. Participation in the all-available sample}} \\\\")
L(" & Participants & Person-waves & 1 / 2 / 3 assessments (\\%) & Retained (\\%) \\\\")
for (g in c("Non-immigrant", "Immigrant")) L("\\quad ", c("Non-immigrant" = "Non-immigrants", Immigrant = "Immigrants")[g], " & ",
  N(ret["n", g]), " & ", N(ret["pw", g]), " & ", sprintf("%.1f / %.1f / %.1f", 100 * ret["k1", g], 100 * ret["k2", g], 100 * ret["k3", g]),
  " & ", sprintf("%.1f", 100 * ret["retained", g]), " \\\\")
tab_close(paste0("All-available sample: $N = ", Nm(length(unique(allsD$id))), "$ participants and ", N(nrow(allsD)),
  " person-waves with all four items observed at the wave and a determinate CLSA Immigration Flag. The same model and reference age ",
  "(62.15 years) as in the primary analysis were used; standard errors are participant-clustered sandwich estimates, and $p$ values are unadjusted. ",
  "Unweighted estimating equations using all available records do not correct for informative dropout; the comparison indicates whether ",
  "conclusions depend on restriction to participants who completed all three assessments. In Panel C, the distribution of assessments ",
  "contributed refers to the all-available sample; ``Retained'' is the percentage of all baseline Comprehensive cohort participants in the ",
  "same Immigration-Flag group who contributed complete physical-activity data at all three assessments (i.e., entered the balanced sample). ",
  "The corresponding cohort denominators are not reported because they would allow a count below six to be derived."))
C(""); C("## Table S10 cross-checks")
C("- all-available block W: ", paste(sprintf("%s %.2f (p %s)", CMP, pA$block["W", ], pv(pA$block["p", ])), collapse = ", "),
  "  (main 35.81, 14.23, 10.65 (.031), 1.02)")
C("- retained at all three, % of baseline cohort in Flag group: non-imm ", sprintf("%.1f", 100 * ret["retained", "Non-immigrant"]),
  "%, imm ", sprintf("%.1f", 100 * ret["retained", "Immigrant"]), "%  (main 83.5 / 80.1); cohort Flag table (local only): ",
  paste(sprintf("%s=%s", names(coh), sapply(as.numeric(coh), function(x) if (x > 0 && x < 6) "<6" else format(x, big.mark = ","))), collapse = ", "))
C("- share with 3 assessments within the all-available sample: non-imm ", sprintf("%.1f", 100 * ret["k3", "Non-immigrant"]),
  "%, imm ", sprintf("%.1f", 100 * ret["k3", "Immigrant"]), "%")
stopifnot(abs(pA$block["W", "beta1"] - 35.81) < .01, abs(pA$block["W", "gamma"] - 10.65) < .01,
          round(100 * ret["retained", "Immigrant"], 1) == 80.1, round(100 * ret["retained", "Non-immigrant"], 1) == 83.5)

# ===========================================================================
# Assessment timing (for Supplementary Methods)
# ===========================================================================
rd <- function(fl, cols) read.csv(file.path(DATA, fl), colClasses = "character", check.names = FALSE)[, c("entity_id", cols)]
x0 <- rd("2310007_UofManitoba_SKim_Baseline_CoPv7_Qx_CANUE_PA.csv", c("startdate_COM", "startdate_MCQ"))
x1 <- rd("2310007_UofManitoba_SKim_FUP1_CoPv5_Qx_CANUE_PA.csv", "startdate_COF1")
x2 <- rd("2310007_UofManitoba_SKim_FUP2_CoPv2_Qx_PA.csv", "startdate_COF2")
ids <- unique(bal$entity_id); dt <- function(x) as.Date(substr(x, 1, 10))
DC <- dt(x0$startdate_COM[match(ids, x0$entity_id)]); D0 <- dt(x0$startdate_MCQ[match(ids, x0$entity_id)])
D1 <- dt(x1$startdate_COF1[match(ids, x1$entity_id)]); D2 <- dt(x2$startdate_COF2[match(ids, x2$entity_id)])
yrs <- function(a, b) as.numeric(b - a) / 365.25; qs <- c(.1, .25, .5, .75, .9)
gaps <- rbind(visit_to_PA = quantile(yrs(DC, D0), qs, na.rm = TRUE), B_to_FU1 = quantile(yrs(D0, D1), qs, na.rm = TRUE),
              FU1_to_FU2 = quantile(yrs(D1, D2), qs, na.rm = TRUE))
C(""); C("## Assessment timing, balanced Flag-determinate sample (years; P10 P25 P50 P75 P90)")
for (r in rownames(gaps)) C("- ", r, ": ", paste(sprintf("%.2f", gaps[r, ]), collapse = " "))
C("- persons with all dates: ", N(sum(!is.na(DC) & !is.na(D0) & !is.na(D1) & !is.na(D2))))

close(con); close(chk)

# Embed the tables in supplementary_results.tex between the GENERATED TABLES
# markers, so the document compiles as a single file. Everything outside the
# markers (preamble, guide, conventions, Table S11) is kept as written.
DOC <- file.path(PKG, "supplementary_results.tex")
doc <- readLines(DOC, encoding = "UTF-8", warn = FALSE)
b <- grep("^% BEGIN GENERATED TABLES", doc); e <- grep("^% END GENERATED TABLES", doc)
if (length(b) != 1 || length(e) != 1 || e <= b) stop("GENERATED TABLES markers not found once each in ", DOC)
out <- file(DOC, open = "wt", encoding = "UTF-8")
writeLines(c(doc[1:b], readLines(FRAG, encoding = "UTF-8"), doc[e:length(doc)]), out)
close(out)
cat("\nwritten: tables S1-S10 embedded in ", DOC, "\n")
